---
title: "HW #4"
author: "Siavash Mortezavi, Jason Liu, Holly Capell, Sangyu Shen, Kunal Kotian"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
---

---------------------------------------------------------------------------

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RPostgreSQL)
library(tidyverse)
library(pastecs)
library(GGally)
drv <- dbDriver("PostgreSQL")
first_database <- dbConnect(drv, dbname = "msan_691", host = "localhost", port = 5432, user = "postgres", password = "postgres")
```


# 4A: Aggregate Functions and Dates

## Q. (1)

(a)

```{r R.options = list(max.print = 10)}
qn_1a <- c("select count(1) from stocks2016.d2010;")
dbGetQuery(first_database,qn_1a)
```

(b)

```{r R.options = list(max.print = 10)}
qn_1b <- c("select count(1) from (select distinct cusip 
  from stocks2016.d2010) as uniqcusips;")
dbGetQuery(first_database,qn_1b)
```

(c)

```{r R.options = list(max.print = 10)}
qn_1c <- c("select count(1) from (select distinct cusip 
from stocks2016.d2011) as uniqcusips;")
dbGetQuery(first_database,qn_1c)
```

(d)

```{r R.options = list(max.print = 10)}
qn_1d <- c("select cusip from
(select cusip, count(1) as ct 
  from stocks2016.d2010 group by cusip) as grouped
where ct < 50;")
dbGetQuery(first_database,qn_1d)
```

(e)

```{r R.options = list(max.print = 10)}
qn_1e <- c("select count(1) from
(select cusip from
(select cusip, count(1) as ct 
  from stocks2016.d2010 group by cusip) as grouped
where ct < 50) as smallcusips;")
dbGetQuery(first_database,qn_1e)
```

(f)

```{r R.options = list(max.print = 10)}
qn_1f <- c("select
sum(case when cusips_count < 50 then 1 else 0 end) as less_than_50,
sum(case when cusips_count > 100 then 1 else 0 end) as more_than_100
from (
select count(cusip) as cusips_count from stocks2016.d2010 
group by cusip) q1;")
dbGetQuery(first_database,qn_1f)
```

(g)

```{r R.options = list(max.print = 10)}
qn_1g <- c("select numtype, count(1)
from
    (select case 
        when cusips_count < 50 then 'less than 50' 
        when cusips_count > 100 then 'greater than 100'
        end as numtype
    from (
    select count(cusip) as cusips_count 
    from stocks2016.d2010 
    group by cusip) q1) q2
where numtype is not null
group by numtype;")
dbGetQuery(first_database,qn_1g)
```


(h)

```{r R.options = list(max.print = 10)}
qn_1h <- c("select numtype, avg(annual_vol) as avg_annual_vol
from
    (select annual_vol, case
        when days_count < 50 then 'less than 50'
        when days_count between 50 and 100 then 'between 50 and 100'
        when days_count > 100 then 'greater than 100'
        end as numtype
    from (
    select cusip, sum(vol) as annual_vol, count(retdate) as days_count
    from stocks2016.d2010
    group by cusip) as q1) as q2
where numtype is not null
group by numtype;")
dbGetQuery(first_database,qn_1h)
```

(i)

```{r R.options = list(max.print = 10)}
qn_1i <- c("select numtype, avg(avg_vol) as avg_annual_vol
from
    (select avg_vol, case
        when days_count < 50 then 'less than 50'
        when days_count between 50 and 100 then 'between 50 and 100'
        when days_count > 100 then 'greater than 100'
        end as numtype
    from (
    select cusip, avg(vol) as avg_vol, count(retdate) as days_count
    from stocks2016.d2010
    group by cusip) as q1) as q2
where numtype is not null
group by numtype;")
dbGetQuery(first_database,qn_1i)
```

(j)

```{r R.options = list(max.print = 10)}
qn_1j <- c("select count(*)
from (select distinct permno
    from (select permno from stocks2016.d2010
        where vol*prc > 100000000 )q1)q2;")
dbGetQuery(first_database,qn_1j)
```

(k)

```{r R.options = list(max.print = 10)}
qn_1k <- c("select count(distinct permno)::float/(select count(distinct permno) 
from stocks2016.d2010) 
from stocks2016.d2010 where prc*vol > 100000000")
dbGetQuery(first_database,qn_1k)
```


## Q. (2)

```{r R.options = list(max.print = 100)}

```


\newpage

# 4B: Aggregation and Dates

## Q. (1)

(a)

```{r R.options = list(max.print = 10)}
qn_2a <- c("select quarter from
    (select case
        when date_part('quarter', retdate) = 1 then 'Q1'
        when date_part('quarter', retdate) = 2 then 'Q2'
        when date_part('quarter', retdate) = 3 then 'Q3'
        when date_part('quarter', retdate) = 4 then 'Q4'
        else null
        end as quarter
    from stocks2016.d2010) as InnerQ
    group by 1
    order by count(quarter) desc limit 1;")
dbGetQuery(first_database,qn_2a)
```

(b)

```{r R.options = list(max.print = 10)}
qn_2b <- ("select permno, max(abs(prc)) as max_price from stocks2016.d2010
where prc is not null
group by permno
order by 2 desc;")
dbGetQuery(first_database,qn_2b)
```

(c)

```{r R.options = list(max.print = 10)}
qn_2c <- ("select permno, case
    when max_price > 100 then 1
    when max_price between 50 and 100 then 2
    when max_price < 50 then 3
    end as DFlag
from
    (select permno, max(abs(prc)) as max_price
    from stocks2016.d2010
    where prc is not null
    group by permno) as InnerQ;")
dbGetQuery(first_database,qn_2c)
```

(d)

```{r R.options = list(max.print = 10)}
qn_2d <- ("select case
    when max_price > 100 then 1
    when max_price between 50 and 100 then 2
    when max_price < 50 then 3
    end as DFlag, count(1) as num_of_permnos
from
    (select permno, max(abs(prc)) as max_price
    from stocks2016.d2010
    where prc is not null
    group by permno) as InnerQ
group by 1;")
dbGetQuery(first_database,qn_2d)
```

(e)

```{r R.options = list(max.print = 10)}
qn_2e <- c("select count(case
    when max_price > 100 then 1
    else null
    end) as count_dflag_1,
    count(case
    when max_price between 50 and 100 then 1
    else null
    end) as count_dflag_2,
    count(case
    when max_price < 50 then 1
    else null
    end) as count_dflag_3
from
    (select permno, max(abs(prc)) as max_price
    from stocks2016.d2010
    where prc is not null
    group by permno) as InnerQ;")
dbGetQuery(first_database,qn_2e)
```


## Q. (2)

```{r R.options = list(max.print = 100)}

```

\newpage

# 4C: Information Schema and Exploring the Relationship between Returns and Dollar Volume

## Q. (1)

(a)

```{r R.options = list(max.print = 10)}
qn_4c1a <- c("select count(1), data_type  from information_schema.columns
group by data_type;")
dbGetQuery(first_database,qn_4c1a)
```

(b)

```{r R.options = list(max.print = 10)}
qn_4c1b <- c("select  distinct(data_type)  from information_schema.columns;")
dbGetQuery(first_database,qn_4c1b)
```

(c)

```{r R.options = list(max.print = 10)}
qn_4c1c <- c("select count(1),data_type,table_schema from information_schema.columns
group by data_type,table_schema;")
dbGetQuery(first_database,qn_4c1c)
```

(d)

<<<<<<< HEAD
```{r R.options = list(max.print = 100)}
qn_4c1d <- c("select table_schema
    ,count(case when data_type ='' then 1 end) as field_blank 
    ,count(case when data_type ='anyarray' then 1 end) as field_array
    ,count(case when data_type ='inet' then 1 end) as field_inet
    ,count(case when data_type ='''char''' then 1 end) as field_char
    ,count(case when data_type ='timestamp with time zone' then 1 end) as field_time
    ,count(case when data_type ='xid' then 1 end) as field_xid
    ,count(case when data_type ='name' then 1 end) as field_name
    ,count(case when data_type ='bytea' then 1 end) as field_byte
    ,count(case when data_type ='date' then 1 end) as field_date
    ,count(case when data_type ='double precision' then 1 end) as field_doub
    ,count(case when data_type ='pg_node_tree' then 1 end) as field_pg_n
    ,count(case when data_type ='real' then 1 end) as field_real
    ,count(case when data_type ='interval' then 1 end) as field_inte
    ,count(case when data_type ='character varying' then 1 end) as field_char
    ,count(case when data_type ='abstime' then 1 end) as field_abst
    ,count(case when data_type ='bigint' then 1 end) as field_bigi
    ,count(case when data_type ='smallint' then 1 end) as field_smal
    ,count(case when data_type ='boolean' then 1 end) as field_bool
    ,count(case when data_type ='integer' then 1 end) as field_inte
    ,count(case when data_type ='ARRAY' then 1 end) as field_ARRA
    ,count(case when data_type ='oid' then 1 end) as field_oid
    ,count(case when data_type ='pg_lsn' then 1 end) as field_pg_l
    ,count(case when data_type ='regproc' then 1 end) as field_regp
    ,count(case when data_type ='text' then 1 end) as field_text
from information_schema.columns
group by 1;")
dbGetQuery(first_database,qn_4c1d)
```
(e)

```{r R.options = list(max.print = 100)}
qn_4c1e <- c("select count(1),data_type,table_schema from information_schema.columns
where table_schema = 'information_schema'
group by data_type,table_schema;")
Query <- dbGetQuery(first_database,qn_4c1e)
Query
pie(unlist(Query[1]),unlist(Query[2]))
```

## Q. (2)

(a)

```{r R.options = list(max.print = 100)}
qn_4c1a <- c("SELECT round(cast(ret as numeric),5)*100 as return, (abs(vol*prc::bigint)/1000)*1000 as dollar_volume  FROM stocks2016.d2010
where ret != 'C' and ret != 'B' and md5(permno::varchar(100)) like '0%';")
new_data <- dbGetQuery(first_database,qn_4c1a)
new_data

```

(b)


```{r R.options = list(max.print = 100)}
plot(new_data$return,new_data$dollar_volume,type = 'p')
```

(c)

```{r R.options = list(max.print = 100)}
case <- lm(formula = new_data$dollar_volume ~ new_data$return)
print(summary(case))
```

#With R approximately 0 there is no apperatn linear relationship between return and dollar volume




