---
title: "HW #5"
author: "Siavash Mortezavi, Jason Liu, Holly Capell, Sangyu Shen, Kunal Kotian"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
---

---------------------------------------------------------------------------

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy = F, 
                      tidy.opts = list(blank = F, width.cutoff = 70))
library(RPostgreSQL)
library(tidyverse)
library(pastecs)
library(GGally)
drv <- dbDriver("PostgreSQL")
first_database <- dbConnect(drv, dbname = "msan_691", host = "localhost", port = 5432, user = "postgres", password = "postgres")
```


# Stock Data Questions

(1)

```{r R.options = list(max.print = 10)}
qn_sd_1 <- c("select lhs.permno, lhs.max_prc as max_prc_2010, rhs.max_prc as max_prc_2011
from 
    (select permno, max(abs(prc)) as max_prc
    from stocks2016.d2010
    group by permno) as lhs
inner join
    (select permno, max(abs(prc)) as max_prc
    from stocks2016.d2011
    group by permno) as rhs
on lhs.permno = rhs.permno;")
dbGetQuery(first_database,qn_sd_1)
```

(2)

```{r R.options = list(max.print = 10)}
qn_sd_2 <- c("select count(lhs.permno) - count(rhs.permno) as num_of_permnos
from
    (select distinct permno from stocks2016.d2010) as lhs
left join
    (select distinct permno from stocks2016.d2011) as rhs
on lhs.permno = rhs.permno;")
dbGetQuery(first_database,qn_sd_2)
```

(3)

```{r R.options = list(max.print = 10)}
qn_sd_3 <- c("select lhs.permno, lhs.date_first, rhs.date_last
from 
    (select permno, min(retdate) as date_first
    from stocks2016.d2010
    group by permno) as lhs
inner join
    (select permno, max(retdate) as date_last
    from stocks2016.d2010
    group by permno) as rhs
on lhs.permno = rhs.permno;")
dbGetQuery(first_database,qn_sd_3)
```

(4)

```{r R.options = list(max.print = 10)}
qn_sd_4 <- c("select lhs.permno, rhs.prc
from
    (select permno, min(retdate) as date_first
    from stocks2016.d2010
    group by permno) as lhs
inner join
    (select * from stocks2016.d2010) as rhs
on lhs.permno = rhs.permno
and lhs.date_first = rhs.retdate;")
dbGetQuery(first_database,qn_sd_4)
```

(5)

```{r R.options = list(max.print = 10)}
qn_sd_5 <- c("select outerlhs.permno, outerlhs.price_first_day, outerrhs.price_last_day
from
    (select lhs.permno, rhs.prc as price_first_day
        from
            (select permno, min(retdate) as date_first
            from stocks2016.d2010
            group by permno) as lhs
        inner join
            (select * from stocks2016.d2010) as rhs
        on lhs.permno = rhs.permno
        and lhs.date_first = rhs.retdate) as outerlhs
inner join
    (select lhs.permno, rhs.prc as price_last_day
        from
            (select permno, max(retdate) as date_last
            from stocks2016.d2010
            group by permno) as lhs
        inner join
            (select * from stocks2016.d2010) as rhs
        on lhs.permno = rhs.permno
        and lhs.date_last = rhs.retdate) as outerrhs
on outerlhs.permno = outerrhs.permno;")
dbGetQuery(first_database,qn_sd_5)
```

(6)

```{r R.options = list(max.print = 10)}
qn_sd_6 <- c("select lhs.permno, rhs.retdate as date_max_vol
from
    (select permno, max(vol) as max_vol
    from stocks2016.d2010
    group by permno) as lhs
inner join
    (select * from stocks2016.d2010) as rhs
on lhs.permno = rhs.permno
and lhs.max_vol = rhs.vol;")
dbGetQuery(first_database,qn_sd_6)
```

(7)

```{r R.options = list(max.print = 10)}
qn_sd_7 <- c("select lhs.permno, rhs.date_first, lhs.retdate
from
    (select * from stocks2016.d2010
    where abs(prc) > 200) as lhs
left join
    (select permno, min(retdate) as date_first
    from stocks2016.d2010
    group by permno) as rhs
on lhs.permno = rhs.permno;")
dbGetQuery(first_database,qn_sd_7)
```

(8)

```{r R.options = list(max.print = 10)}
qn_sd_8 <- c("select date_part('year',retdate) as year, 
date_part('dow',retdate) as dow, avg(abs(prc)) as avgprc
    from stocks2016.d2010
    group by dow, year
union
select date_part('year',retdate) as year,
date_part('dow',retdate) as dow, avg(abs(prc)) as avgprc
    from stocks2016.d2011
    group by dow, year
order by year;")
dbGetQuery(first_database,qn_sd_8)
```

(9)

```{r R.options = list(max.print = 10)}
qn_sd_9 <- c("select yr2010.dow, yr2010.avgprc2010, yr2011.avgprc2011   
from
    (select date_part('year',retdate) as year,
date_part('dow',retdate) as dow, avg(abs(prc)) as avgprc2010
    from stocks2016.d2010
    group by dow, year) as yr2010
join
    (select date_part('year',retdate) as year,
date_part('dow',retdate) as dow, avg(abs(prc)) as avgprc2011
    from stocks2016.d2011
    group by dow, year) as yr2011
on yr2010.dow = yr2011.dow;")
dbGetQuery(first_database,qn_sd_9)
```

(10)

```{r R.options = list(max.print = 10)}
qn_sd_10 <- c("select lhs.permno, avg(lhs.tues/rhs.mon - 1)*100 as avgprc
from
    (select permno, retdate, abs(prc) as tues
    from stocks2016.d2010 where date_part('dow', retdate) = 2) as lhs
join
    (select permno, retdate, abs(prc) as mon
    from stocks2016.d2010 where date_part('dow', retdate) = 1) as rhs
on lhs.permno = rhs.permno
and lhs.retdate = rhs.retdate + 1
group by lhs.permno;")
dbGetQuery(first_database,qn_sd_10)
```

(11)

```{r R.options = list(max.print = 10)}
qn_sd_11 <- c("select lhs.permno, rhs.first_date, lhs.last_date
from
    (select permno, min(retdate) as first_date
    from stocks2016.d2010
    group by permno) as rhs
join
    (select permno, max(retdate) as last_date
    from stocks2016.d2011
    group by permno) as lhs
on rhs.permno = lhs.permno;")
dbGetQuery(first_database,qn_sd_11)
```


# MTA Data Questions

(1)

```{r R.options = list(max.print = 10)}
MTA_Q1 <- c("select count(distinct plaza)
from cls.mta;")
dbGetQuery(first_database,MTA_Q1)
```

(2)

```{r R.options = list(max.print = 10)}
MTA_Q2 <- c("select plaza, avg(ez + cash)
from --get the avg number of car of any day for any plaza 
    (select plaza,mtadt,avg(vehiclesez) as ez, avg(vehiclescash) as cash
    from cls.mta
    group by plaza,mtadt)as q1
group by plaza ;")
dbGetQuery(first_database,MTA_Q2)
```

(3)

```{r R.options = list(max.print = 10)}
MTA_Q3 <- c("select date_part('dow', mtadt) as day_of_week, sum(vehiclesez)as sum
from cls.mta
where plaza = 1 
group by day_of_week
order by sum desc
limit 1;")
dbGetQuery(first_database,MTA_Q3)
```

(4)

```{r R.options = list(max.print = 10)}
MTA_Q4 <- c("select day_of_week,plaza, ez/(cash+ez) ::float as ratio
from(
    select date_part('dow', mtadt) as day_of_week, plaza, 
            sum(vehiclesez) as ez, sum(vehiclescash) as cash
    from cls.mta
    where direction = 'O'
    group by day_of_week, plaza)as q1
order by ratio 
limit 1;")
dbGetQuery(first_database,MTA_Q4)
```

(5)

```{r R.options = list(max.print = 10)}
MTA_Q5 <- c("select date_part('dow', mtadt) as day_of_week, avg(vehiclesez)
from cls.mta 
where plaza = 1 and direction = 'O'
group by day_of_week
order by day_of_week;")
dbGetQuery(first_database,MTA_Q5)
```

(6)

```{r R.options = list(max.print = 10)}
MTA_Q6 <- c("select day_of_week, ez/(cash+ez) ::float as ratio
from(
    select date_part('dow', mtadt) as day_of_week, plaza, 
            sum(vehiclesez) as ez, sum(vehiclescash) as cash
    from cls.mta
    where direction = 'O'
    group by day_of_week, plaza)as q1
where plaza = 1
order by day_of_week;")
dbGetQuery(first_database,MTA_Q6)
```

