---
title: "Homework #6"
output: pdf_document
authors: Siavash Mortezavi, Jason Liu, Holly Capell, Sangyu Shen, Kunal Kotian
date: October 5, 2017
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy = F, 
                      tidy.opts = list(blank = F, width.cutoff = 70))
library(RPostgreSQL)
library(tidyverse)
library(pastecs)
library(GGally)
require("RPostgreSQL")
drv <- dbDriver("PostgreSQL")
first_database <- dbConnect(drv, dbname = "msan_691", host = "localhost", port = 5432, user = "postgres", password = "postgres")

```

####Stock Questions

(1)

```{r R.options = list(max.print = 10)}
q_1 <- c("select avg(ret::numeric)
from
(select count(1) over () as total, ROW_NUMBER() over (order by ret), ret
from stocks2016.d2010
where 
retdate = '2010-01-04' and ret != 'B' and ret!= 'C') as lhs
where ROW_NUMBER in ((total+1)/2,(total + 2)/2);")
dbGetQuery(first_database, q_1)
```

(2)

```{r R.options = list(max.print = 10)}
q_2 <- c("select count(permno), round(sumOfVol) as sv 
FROM
    (select permno, log(sum(vol)) as sumOfVol 
    FROM stocks2016.d2010 
    where date_part('year', retdate) = 2010 and vol!=0 
    group by permno) as LHS
group by 2;")
frq2 = dbGetQuery(first_database,q_2)
frq2 %>% ggplot() + geom_bar(aes(x = frq2$sv, y = frq2$count), stat = "identity") + xlab('Log of Total Volume Per Stock') + ylab('Frequency')
```

(3)

```{r R.options = list(max.print = 10)}
qn_pt1_3 <- c("select sum(count) over (ORDER BY sv) as cumul_sum, sv 
FROM
    (select count(permno), round(log(sumOfVol)) as sv 
    FROM
        (select permno, sum(vol) as sumOfVol 
        FROM stocks2016.d2010 
        where date_part('year', retdate) = 2010 and vol!=0 group by permno) as LHS
    group by sv) as allof;")
frq3 = dbGetQuery(first_database,qn_pt1_3)
frq3 %>% ggplot() + geom_bar(aes(x = frq3$sv, y = frq3$cumul_sum), stat = "identity") + xlab('Log of Total Volume Per Stock') + ylab('Cumulative Frequency')
```

(4)

```{r R.options = list(max.print = 10)}
# Extract data for plotting
q_4 <- c("select log(sumOfVol) as logSumofVol, log(sum(log(sumOfVol)) over(order by log(sumOfVol))) as cumlogSumofVol
from 
    (select sum(vol) as sumOfVol
    from stocks2016.d2010
    where vol <> 0
    group by permno) as InnerQ;")
(frq4 = dbGetQuery(first_database, q_4))
```


```{r}
# Generate plots:
# PDF of the distribution of the log of total volume per stock
frq4 %>% ggplot(aes(x = frq4$logsumofvol)) + stat_density(geom = "step") + xlab('Log of Total Volume Per Stock') + ylab('Probability Density')
# CDF of the distribution of the cumulative log of total volume per stock
frq4 %>% ggplot(aes(x = frq4$cumlogsumofvol)) + stat_ecdf(geom = "step", pad = "FALSE") + xlab('Log of Total Volume Per Stock') + ylab('Cumulative Probability Density')
```

(5)

```{r R.options = list(max.print = 10)}
q_5 <- c("select tic, count(tic) over(order by tic) -1 as count from stocks2016.fnd
where fyear = 2010 and tic is not null and tic >= 'A'
order by tic;")
dbGetQuery(first_database, q_5)
```

(6)

```{r R.options = list(max.print = 10)}
q_6 <- c("select diff, case when diff > 0 then 1 else 0 end, count(0) over(partition by diff)
from
(select permno, retdate, c2-c1 as diff
from
(select permno, retdate, 
first_value(prc) over(partition by date_part('month',retdate)) as c1,
last_value(prc) over(partition by date_part('month',retdate)) as c2 
from stocks2016.d2010) as c3) as c4
limit 500;")
dbGetQuery(first_database, q_6)
```

(7)

```{r R.options = list(max.print = 10)}
q_7 <- c("select prc, permno, permco, retdate,
prc - lag(prc) over () as nominal_diff
from stocks2016.d2010
where prc is not null;")
dbGetQuery(first_database, q_7)
```

(8)

```{r R.options = list(max.print = 10)}
q_8 <- c("select RHS2.prc, LHS.permno, LHS.permco, RHS2.retdate,
RHS2.prc - lag(RHS2.prc) over (partition by LHS.permno,LHS.permco) as nominal_diff
from 
(select distinct permno, permco from stocks2016.d2010) as LHS
cross join
(select distinct retdate from stocks2016.d2010) as RHS
left join stocks2016.d2010 as RHS2
on LHS.permno = RHS2.permno and LHS.permco = RHS2.permco and RHS.retdate = RHS2.retdate;")
dbGetQuery(first_database, q_8)
```

(9)

```{r R.options = list(max.print = 10)}
q_9 <- c("select permno,permco,  sum(case1) 
from
(
select permno, permco, case when prc >= max_9 then 1 else 0 end as case1
from
(
select permno,permco, prc, .9*max(prc) over(partition by permno)as max_9
from stocks2016.d2010) as lhs) as more
group by permno, permco;")
dbGetQuery(first_database, q_9)
```

(10)

```{r R.options = list(max.print = 10)}
q_10 <- c("select lhs.retdate,lhs.permno, lhs.permco, lhs.prc, lhs.row_num as numberofdays
from 
(select retdate,permno, permco, prc, ROW_NUMBER() over(partition by permno, permco order by retdate) as row_num
,max(prc) over(partition by permno, permco) as maxp
from stocks2016.d2010 order by permno, permco, retdate) as lhs
where lhs.prc = lhs.maxp;
")
dbGetQuery(first_database, q_10)
```

(11)

```{r R.options = list(max.print = 10)}
q_11 <- c("select permno, permco, numdays
from(
select permno, permco, retdate as date1, sum(difdays) over (partition by permno, permco order
by retdate asc) as numdays, prc, maximum
from(
select permno, permco, retdate, case when retdate - lag(retdate) over () > 0 
then retdate - lag(retdate) over ()
else Null end as difdays, 
prc, max(prc) over(partition by permco, permno) as maximum 
from stocks2016.d2010
order by permno, permco, retdate
limit 10000) as table1) as table2
where maximum = prc;")
dbGetQuery(first_database, q_11)
```

####LTV Questions

(1)

```{r R.options = list(max.print = 10)}
q_LTV1 <- c("select RHS.purchased_sub::float/LHS.first_purchase_unit as percent from
(select count(distinct userid) as first_purchase_unit from
(select 
userid, transtype,
first_value(transtype) over (partition by userid order by dt) as first_purchase
from cls.ltv) q1
where first_purchase = 'Unit') as LHS
cross join
(select count(distinct userid) as purchased_sub from
(select 
userid, transtype,
first_value(transtype) over (partition by userid order by dt) as first_purchase
from cls.ltv) q1
where first_purchase = 'Unit' and transtype = 'Subscription') as RHS;")
dbGetQuery(first_database, q_LTV1)
```


(2)

```{r R.options = list(max.print = 10)}
q_LTV2 <- c("select distinct(userid) from
(select userid from cls.ltv where transtype = 'Unit') as LHS
inner join
(select userid from cls.ltv where transtype = 'Subscription') as RHS
using(userid);")
dbGetQuery(first_database, q_LTV2)
```


(3)

```{r R.options = list(max.print = 10)}
q_LTV3 <- c("select avg(time_diff) from
(select dt - lag(dt) over (partition by userid order by dt) as time_diff from cls.ltv 
where transtype = 'Unit') q1
where time_diff is not null;")
dbGetQuery(first_database, q_LTV3)
```

(4)

```{r R.options = list(max.print = 10)}
q_LTV4 <- c("select avg(time_diff) from
(select count(1) over () as total, row_number() over (order by time_diff), time_diff from
(select dt - lag(dt) over (partition by userid order by dt) as time_diff from cls.ltv 
where transtype = 'Unit') q1
where time_diff is not null)q2
where row_number in ((total+1)/2,(total + 2)/2);")
dbGetQuery(first_database, q_LTV4)
```


(5)

```{r R.options = list(max.print = 10)}
q_LTV5 <- c("")
dbGetQuery(first_database, q_LTV5)
```


